from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timedelta, timezone


class LCARepository:
    """Persistence and relevant-event processing for Lighting Context Analytics.

    MQTT publications are telemetry. They only become analytical events when a
    channel actually changes state or an explicit physical interaction is
    observed.
    """

    def __init__(self, db):
        self.db = db
        self.ensure_schema()
        self._migrate_010_history()

    def ensure_schema(self):
        with self.db.connect() as c:
            c.executescript(
                """
                CREATE TABLE IF NOT EXISTS lca_devices(
                  device_id TEXT PRIMARY KEY, site_id TEXT NOT NULL, name TEXT NOT NULL, topic TEXT,
                  model TEXT, manufacturer TEXT, device_type TEXT NOT NULL DEFAULT 'unknown', status TEXT NOT NULL DEFAULT 'discovered',
                  location_id TEXT, location_name TEXT, adjacent_location_id TEXT, adjacent_location_name TEXT,
                  position_label TEXT, notes TEXT, availability TEXT NOT NULL DEFAULT 'unknown',
                  first_seen TEXT NOT NULL, last_seen TEXT NOT NULL, sample_payload_json TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL);
                CREATE TABLE IF NOT EXISTS lca_channels(
                  channel_id TEXT PRIMARY KEY, device_id TEXT NOT NULL, channel_key TEXT NOT NULL, name TEXT,
                  interaction_point TEXT, location_id TEXT, location_name TEXT, adjacent_location_id TEXT, adjacent_location_name TEXT,
                  direction_hint TEXT, related_light_id TEXT, related_light_name TEXT, virtual_parallel_group TEXT,
                  enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
                  FOREIGN KEY(device_id) REFERENCES lca_devices(device_id) ON DELETE CASCADE);
                CREATE UNIQUE INDEX IF NOT EXISTS idx_lca_channel_unique ON lca_channels(device_id,channel_key);
                CREATE TABLE IF NOT EXISTS lca_events(
                  id INTEGER PRIMARY KEY AUTOINCREMENT, lca_event_id TEXT NOT NULL UNIQUE, device_id TEXT NOT NULL,
                  channel_key TEXT, kind TEXT NOT NULL, state TEXT, action TEXT, brightness REAL, occurred_at TEXT NOT NULL,
                  origin_location_id TEXT, origin_location_name TEXT, adjacent_location_id TEXT, adjacent_location_name TEXT,
                  direction_hint TEXT, related_light_id TEXT, related_light_name TEXT, virtual_parallel_group TEXT,
                  payload_json TEXT NOT NULL, created_at TEXT NOT NULL);
                CREATE INDEX IF NOT EXISTS idx_lca_events_time ON lca_events(occurred_at DESC);
                CREATE INDEX IF NOT EXISTS idx_lca_events_device_time ON lca_events(device_id,occurred_at DESC);
                CREATE TABLE IF NOT EXISTS lca_sessions(
                  session_id TEXT PRIMARY KEY, device_id TEXT NOT NULL, channel_key TEXT, related_light_id TEXT,
                  started_at TEXT NOT NULL, ended_at TEXT, duration_seconds INTEGER, start_event_id TEXT NOT NULL,
                  end_event_id TEXT, status TEXT NOT NULL DEFAULT 'open', updated_at TEXT NOT NULL);
                CREATE INDEX IF NOT EXISTS idx_lca_sessions_start ON lca_sessions(started_at DESC);

                CREATE TABLE IF NOT EXISTS lca_channel_state(
                  device_id TEXT NOT NULL, channel_key TEXT NOT NULL, state TEXT NOT NULL,
                  brightness REAL, first_observed_at TEXT NOT NULL, last_observed_at TEXT NOT NULL,
                  last_changed_at TEXT, updated_at TEXT NOT NULL,
                  PRIMARY KEY(device_id, channel_key));

                CREATE TABLE IF NOT EXISTS lca_messages(
                  message_id TEXT PRIMARY KEY, device_id TEXT NOT NULL, topic TEXT,
                  occurred_at TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL);
                CREATE INDEX IF NOT EXISTS idx_lca_messages_time ON lca_messages(occurred_at DESC);

                CREATE TABLE IF NOT EXISTS lca_metadata(
                  key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);

                CREATE TABLE IF NOT EXISTS lca_device_exclusions(
                  device_id TEXT PRIMARY KEY, reason TEXT,
                  created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
                """
            )

    def _migrate_010_history(self):
        """Remove only the synthetic state history generated by LCA 0.1.0.

        Interactions and availability evidence are retained. The migration runs
        once and initializes current state again from fresh MQTT observations.
        """
        key = "relevant_event_processing_011"
        with self.db.connect() as c:
            done = c.execute("SELECT value FROM lca_metadata WHERE key=?", (key,)).fetchone()
            if done:
                return
            c.execute("DELETE FROM lca_sessions")
            c.execute("DELETE FROM lca_events WHERE kind='state'")
            c.execute("DELETE FROM lca_channel_state")
            now = datetime.now(timezone.utc).isoformat()
            c.execute(
                "INSERT INTO lca_metadata(key,value,updated_at) VALUES(?,?,?)",
                (key, "completed", now),
            )

    def ingest(self, items):
        inserted_events = 0
        if not items:
            return inserted_events
        with self.db.connect() as c:
            for item in items:
                now = datetime.now(timezone.utc).isoformat()
                did = item["device_id"]
                ch = item.get("channel")
                blocked = c.execute(
                    "SELECT 1 FROM lca_device_exclusions WHERE device_id=?", (did,)
                ).fetchone()
                ignored = c.execute(
                    "SELECT 1 FROM lca_devices WHERE device_id=? AND status='ignored'", (did,)
                ).fetchone()
                if blocked or ignored:
                    continue
                self._upsert_device(c, item, now)
                if ch:
                    self._upsert_channel(c, did, ch, now)
                self._record_message(c, item, now)
                cfg = (
                    c.execute(
                        "SELECT * FROM lca_channels WHERE device_id=? AND channel_key=?",
                        (did, ch),
                    ).fetchone()
                    if ch
                    else None
                )

                kind = item["kind"]
                if kind == "state":
                    if self._process_state(c, item, cfg, now):
                        inserted_events += 1
                elif kind == "availability":
                    if self._process_availability(c, item, cfg, now):
                        inserted_events += 1
                elif kind == "interaction":
                    if self._process_interaction(c, item, cfg, now):
                        inserted_events += 1
        return inserted_events

    def _upsert_device(self, c, item, now):
        c.execute(
            """INSERT INTO lca_devices(device_id,site_id,name,topic,model,manufacturer,first_seen,last_seen,sample_payload_json,updated_at)
               VALUES(?,?,?,?,?,?,?,?,?,?)
               ON CONFLICT(device_id) DO UPDATE SET
                 name=COALESCE(NULLIF(excluded.name,''),lca_devices.name),
                 topic=COALESCE(excluded.topic,lca_devices.topic),
                 model=COALESCE(excluded.model,lca_devices.model),
                 manufacturer=COALESCE(excluded.manufacturer,lca_devices.manufacturer),
                 last_seen=excluded.last_seen,
                 sample_payload_json=excluded.sample_payload_json,
                 updated_at=excluded.updated_at""",
            (
                item["device_id"], self.db.site_id, item["device_name"], item.get("topic"),
                item.get("model"), item.get("manufacturer"), item["occurred_at"],
                item["occurred_at"], json.dumps(item["payload"], ensure_ascii=False), now,
            ),
        )

    @staticmethod
    def _upsert_channel(c, did, ch, now):
        cid = f"{did}:{ch}"
        c.execute(
            """INSERT INTO lca_channels(channel_id,device_id,channel_key,created_at,updated_at)
               VALUES(?,?,?,?,?) ON CONFLICT(device_id,channel_key)
               DO UPDATE SET updated_at=excluded.updated_at""",
            (cid, did, ch, now, now),
        )

    @staticmethod
    def _record_message(c, item, now):
        message_id = item.get("message_id") or item["lca_event_id"].split(":", 1)[0]
        try:
            c.execute(
                "INSERT INTO lca_messages(message_id,device_id,topic,occurred_at,payload_json,created_at) VALUES(?,?,?,?,?,?)",
                (message_id, item["device_id"], item.get("topic"), item["occurred_at"],
                 json.dumps(item["payload"], ensure_ascii=False), now),
            )
        except sqlite3.IntegrityError:
            pass

    def _process_state(self, c, item, cfg, now):
        did, ch, new_state = item["device_id"], item.get("channel") or "main", item["state"]
        previous = c.execute(
            "SELECT * FROM lca_channel_state WHERE device_id=? AND channel_key=?",
            (did, ch),
        ).fetchone()

        # First observation establishes baseline only. It is not an event.
        if previous is None:
            c.execute(
                """INSERT INTO lca_channel_state(device_id,channel_key,state,brightness,first_observed_at,last_observed_at,last_changed_at,updated_at)
                   VALUES(?,?,?,?,?,?,NULL,?)""",
                (did, ch, new_state, item.get("brightness"), item["occurred_at"], item["occurred_at"], now),
            )
            return False

        # Repeated state report: update telemetry timestamp, produce no event.
        if previous["state"] == new_state:
            c.execute(
                """UPDATE lca_channel_state SET brightness=COALESCE(?,brightness),last_observed_at=?,updated_at=?
                   WHERE device_id=? AND channel_key=?""",
                (item.get("brightness"), item["occurred_at"], now, did, ch),
            )
            return False

        event = dict(item)
        event["kind"] = "state_change"
        event["action"] = f"{previous['state']}->{new_state}"
        event["lca_event_id"] = item["lca_event_id"] + ":change"
        if not self._insert_event(c, event, cfg, now):
            return False

        c.execute(
            """UPDATE lca_channel_state SET state=?,brightness=?,last_observed_at=?,last_changed_at=?,updated_at=?
               WHERE device_id=? AND channel_key=?""",
            (new_state, item.get("brightness"), item["occurred_at"], item["occurred_at"], now, did, ch),
        )
        self._update_session(c, event, cfg, now)
        return True

    def _process_availability(self, c, item, cfg, now):
        current = c.execute("SELECT availability FROM lca_devices WHERE device_id=?", (item["device_id"],)).fetchone()
        previous = current["availability"] if current else "unknown"
        c.execute(
            "UPDATE lca_devices SET availability=?,updated_at=? WHERE device_id=?",
            (item["state"], now, item["device_id"]),
        )
        if previous in {"unknown", item["state"]}:
            return False
        event = dict(item)
        event["kind"] = "availability_change"
        event["action"] = f"{previous}->{item['state']}"
        return self._insert_event(c, event, cfg, now)

    def _process_interaction(self, c, item, cfg, now):
        # Some devices repeat the same action in consecutive reports. Ignore an
        # identical interaction observed within a short anti-bounce window.
        cutoff = self._parse_time(item["occurred_at"]) - timedelta(seconds=2)
        recent = c.execute(
            """SELECT occurred_at FROM lca_events
               WHERE device_id=? AND channel_key IS ? AND kind='interaction' AND action=?
               ORDER BY occurred_at DESC LIMIT 1""",
            (item["device_id"], item.get("channel"), item.get("action")),
        ).fetchone()
        if recent and self._parse_time(recent["occurred_at"]) >= cutoff:
            return False
        return self._insert_event(c, item, cfg, now)

    @staticmethod
    def _parse_time(value):
        try:
            return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return datetime.now(timezone.utc)

    @staticmethod
    def _insert_event(c, item, cfg, now):
        try:
            c.execute(
                """INSERT INTO lca_events(lca_event_id,device_id,channel_key,kind,state,action,brightness,occurred_at,
                   origin_location_id,origin_location_name,adjacent_location_id,adjacent_location_name,direction_hint,
                   related_light_id,related_light_name,virtual_parallel_group,payload_json,created_at)
                   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    item["lca_event_id"], item["device_id"], item.get("channel"), item["kind"],
                    item.get("state"), item.get("action"), item.get("brightness"), item["occurred_at"],
                    cfg["location_id"] if cfg else None, cfg["location_name"] if cfg else None,
                    cfg["adjacent_location_id"] if cfg else None, cfg["adjacent_location_name"] if cfg else None,
                    cfg["direction_hint"] if cfg else None, cfg["related_light_id"] if cfg else None,
                    cfg["related_light_name"] if cfg else None, cfg["virtual_parallel_group"] if cfg else None,
                    json.dumps(item["payload"], ensure_ascii=False), now,
                ),
            )
            return True
        except sqlite3.IntegrityError:
            return False

    def _update_session(self, c, item, cfg, now):
        did, ch = item["device_id"], item.get("channel")
        light = cfg["related_light_id"] if cfg else None
        open_row = c.execute(
            """SELECT * FROM lca_sessions WHERE device_id=? AND channel_key IS ? AND status='open'
               ORDER BY started_at DESC LIMIT 1""",
            (did, ch),
        ).fetchone()
        if item["state"] == "on" and not open_row:
            sid = f"{did}:{ch or 'main'}:{item['occurred_at']}"
            c.execute(
                """INSERT OR IGNORE INTO lca_sessions(session_id,device_id,channel_key,related_light_id,started_at,start_event_id,status,updated_at)
                   VALUES(?,?,?,?,?,?,?,?)""",
                (sid, did, ch, light, item["occurred_at"], item["lca_event_id"], "open", now),
            )
        elif item["state"] == "off" and open_row:
            start = self._parse_time(open_row["started_at"])
            end = self._parse_time(item["occurred_at"])
            duration = max(0, int((end - start).total_seconds()))
            c.execute(
                """UPDATE lca_sessions SET ended_at=?,duration_seconds=?,end_event_id=?,status='closed',updated_at=?
                   WHERE session_id=?""",
                (item["occurred_at"], duration, item["lca_event_id"], now, open_row["session_id"]),
            )

    @staticmethod
    def _configured_channel_count(c, did):
        return c.execute(
            """SELECT COUNT(*) FROM lca_channels
               WHERE device_id=? AND enabled=1
                 AND COALESCE(NULLIF(TRIM(name),''),NULLIF(TRIM(related_light_name),'')) IS NOT NULL
                 AND (NULLIF(TRIM(interaction_point),'') IS NOT NULL
                      OR NULLIF(TRIM(adjacent_location_name),'') IS NOT NULL
                      OR NULLIF(TRIM(direction_hint),'') IS NOT NULL)""",
            (did,),
        ).fetchone()[0]

    @classmethod
    def _refresh_configuration_status(cls, c, did):
        row = c.execute("SELECT status,location_name FROM lca_devices WHERE device_id=?", (did,)).fetchone()
        if not row or row["status"] == "ignored":
            return
        total = c.execute("SELECT COUNT(*) FROM lca_channels WHERE device_id=? AND enabled=1", (did,)).fetchone()[0]
        configured = cls._configured_channel_count(c, did)
        if row["location_name"] and total > 0 and configured == total:
            status = "configured"
        elif row["location_name"] or configured > 0:
            status = "incomplete"
        else:
            status = "discovered"
        c.execute("UPDATE lca_devices SET status=? WHERE device_id=?", (status, did))

    def devices(self, include_ignored=False):
        with self.db.connect() as c:
            where = "" if include_ignored else "WHERE d.status<>'ignored'"
            rows = c.execute(
                f"""SELECT d.*,
                          (SELECT COUNT(*) FROM lca_channels x WHERE x.device_id=d.device_id) channel_count,
                          (SELECT COUNT(*) FROM lca_channels x WHERE x.device_id=d.device_id AND x.enabled=1
                             AND COALESCE(NULLIF(TRIM(x.name),''),NULLIF(TRIM(x.related_light_name),'')) IS NOT NULL
                             AND (NULLIF(TRIM(x.interaction_point),'') IS NOT NULL
                                  OR NULLIF(TRIM(x.adjacent_location_name),'') IS NOT NULL
                                  OR NULLIF(TRIM(x.direction_hint),'') IS NOT NULL)) configured_channel_count
                   FROM lca_devices d
                   {where}
                   ORDER BY CASE d.status WHEN 'discovered' THEN 0 WHEN 'incomplete' THEN 1 WHEN 'configured' THEN 2 ELSE 3 END,d.name"""
            ).fetchall()
            return [dict(r) for r in rows]

    def device(self, did):
        with self.db.connect() as c:
            d = c.execute("SELECT * FROM lca_devices WHERE device_id=?", (did,)).fetchone()
            if not d:
                return None
            channels = c.execute("SELECT * FROM lca_channels WHERE device_id=? ORDER BY channel_key", (did,)).fetchall()
            out = dict(d)
            out["channels"] = [dict(x) for x in channels]
            out["configured_channel_count"] = self._configured_channel_count(c, did)
            out["channel_count"] = len(channels)
            return out

    def update_device(self, did, p):
        allowed = ["name", "device_type", "status", "location_id", "location_name", "adjacent_location_id", "adjacent_location_name", "position_label", "notes"]
        fields = [k for k in allowed if k in p]
        if not fields:
            return self.device(did)
        with self.db.connect() as c:
            exists = c.execute("SELECT 1 FROM lca_devices WHERE device_id=?", (did,)).fetchone()
            if not exists:
                return None
            now = datetime.now(timezone.utc).isoformat()
            vals = [p[k] for k in fields] + [now, did]
            c.execute(f"UPDATE lca_devices SET {','.join(k+'=?' for k in fields)},updated_at=? WHERE device_id=?", vals)
            if p.get("status") == "ignored":
                c.execute(
                    "INSERT INTO lca_device_exclusions(device_id,reason,created_at,updated_at) VALUES(?,?,?,?) "
                    "ON CONFLICT(device_id) DO UPDATE SET reason=excluded.reason,updated_at=excluded.updated_at",
                    (did, "ignored_by_user", now, now),
                )
            elif "status" in p and p.get("status") != "ignored":
                c.execute("DELETE FROM lca_device_exclusions WHERE device_id=?", (did,))
            self._refresh_configuration_status(c, did)
        return self.device(did)

    def ignored_devices(self):
        with self.db.connect() as c:
            rows = c.execute(
                """SELECT d.*,
                          (SELECT COUNT(*) FROM lca_channels x WHERE x.device_id=d.device_id) channel_count,
                          (SELECT COUNT(*) FROM lca_events e WHERE e.device_id=d.device_id) historical_event_count
                   FROM lca_devices d WHERE d.status='ignored' ORDER BY d.name"""
            ).fetchall()
            return [dict(r) for r in rows]

    def reactivate_device(self, did):
        with self.db.connect() as c:
            exists = c.execute("SELECT 1 FROM lca_devices WHERE device_id=?", (did,)).fetchone()
            if not exists:
                return None
            now = datetime.now(timezone.utc).isoformat()
            c.execute("DELETE FROM lca_device_exclusions WHERE device_id=?", (did,))
            c.execute("UPDATE lca_devices SET status='discovered',updated_at=? WHERE device_id=?", (now, did))
            self._refresh_configuration_status(c, did)
        return self.device(did)

    def remove_device(self, did, preserve_history=True, ignore_future=False):
        with self.db.connect() as c:
            exists = c.execute("SELECT 1 FROM lca_devices WHERE device_id=?", (did,)).fetchone()
            if not exists:
                return False
            now = datetime.now(timezone.utc).isoformat()
            if ignore_future:
                c.execute(
                    "INSERT INTO lca_device_exclusions(device_id,reason,created_at,updated_at) VALUES(?,?,?,?) "
                    "ON CONFLICT(device_id) DO UPDATE SET reason=excluded.reason,updated_at=excluded.updated_at",
                    (did, "removed_and_blocked", now, now),
                )
            else:
                c.execute("DELETE FROM lca_device_exclusions WHERE device_id=?", (did,))
            c.execute("DELETE FROM lca_sessions WHERE device_id=?", (did,))
            c.execute("DELETE FROM lca_channel_state WHERE device_id=?", (did,))
            c.execute("DELETE FROM lca_messages WHERE device_id=?", (did,))
            c.execute("DELETE FROM lca_channels WHERE device_id=?", (did,))
            if not preserve_history:
                c.execute("DELETE FROM lca_events WHERE device_id=?", (did,))
            c.execute("DELETE FROM lca_devices WHERE device_id=?", (did,))
        return True

    def update_channel(self, did, ch, p):
        allowed = ["name", "interaction_point", "location_id", "location_name", "adjacent_location_id", "adjacent_location_name", "direction_hint", "related_light_id", "related_light_name", "virtual_parallel_group", "enabled"]
        fields = [k for k in allowed if k in p]
        with self.db.connect() as c:
            now = datetime.now(timezone.utc).isoformat()
            cid = f"{did}:{ch}"
            c.execute("INSERT OR IGNORE INTO lca_channels(channel_id,device_id,channel_key,created_at,updated_at) VALUES(?,?,?,?,?)", (cid, did, ch, now, now))
            if fields:
                vals = [1 if p[k] is True else 0 if p[k] is False else p[k] for k in fields] + [now, did, ch]
                c.execute(f"UPDATE lca_channels SET {','.join(k+'=?' for k in fields)},updated_at=? WHERE device_id=? AND channel_key=?", vals)
            self._refresh_configuration_status(c, did)
        return self.device(did)

    def events(self, hours=24, limit=200, device_id=None):
        since = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
        where, params = ["occurred_at>=?"], [since]
        if device_id:
            where.append("device_id=?")
            params.append(device_id)
        params.append(limit)
        with self.db.connect() as c:
            query = f"""SELECT e.* FROM lca_events e JOIN lca_devices d ON d.device_id=e.device_id
                        WHERE {' AND '.join('e.'+w if w.startswith('occurred_at') or w.startswith('device_id') else w for w in where)}
                          AND d.status<>'ignored' ORDER BY e.occurred_at DESC LIMIT ?"""
            return [dict(r) for r in c.execute(query, params).fetchall()]

    def dashboard(self, hours=24):
        since = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
        with self.db.connect() as c:
            totals = dict(c.execute("""SELECT COUNT(*) events,COUNT(DISTINCT e.device_id) active_devices
                FROM lca_events e JOIN lca_devices d ON d.device_id=e.device_id
                WHERE e.occurred_at>=? AND d.status<>'ignored'""", (since,)).fetchone())
            totals["messages_received"] = c.execute("SELECT COUNT(*) FROM lca_messages WHERE occurred_at>=?", (since,)).fetchone()[0]
            totals["discovered_devices"] = c.execute("SELECT COUNT(*) FROM lca_devices WHERE status<>'ignored'").fetchone()[0]
            totals["ignored_devices"] = c.execute("SELECT COUNT(*) FROM lca_devices WHERE status='ignored'").fetchone()[0]
            totals["unconfigured_devices"] = c.execute("SELECT COUNT(*) FROM lca_devices WHERE status IN ('discovered','incomplete')").fetchone()[0]
            totals["interactions"] = c.execute("""SELECT COUNT(*) FROM lca_events e JOIN lca_devices d ON d.device_id=e.device_id
                WHERE e.occurred_at>=? AND e.kind='interaction' AND d.status<>'ignored'""", (since,)).fetchone()[0]
            totals["state_changes"] = c.execute("""SELECT COUNT(*) FROM lca_events e JOIN lca_devices d ON d.device_id=e.device_id
                WHERE e.occurred_at>=? AND e.kind='state_change' AND d.status<>'ignored'""", (since,)).fetchone()[0]
            totals["open_sessions"] = c.execute("""SELECT COUNT(*) FROM lca_sessions s JOIN lca_devices d ON d.device_id=s.device_id
                WHERE s.status='open' AND d.status<>'ignored'""").fetchone()[0]
            by_hour = [dict(r) for r in c.execute("""SELECT substr(e.occurred_at,1,13)||':00' bucket,COUNT(*) value
                FROM lca_events e JOIN lca_devices d ON d.device_id=e.device_id
                WHERE e.occurred_at>=? AND d.status<>'ignored' GROUP BY bucket ORDER BY bucket""", (since,)).fetchall()]
            top = [dict(r) for r in c.execute("SELECT COALESCE(d.name,e.device_id) name,e.device_id,COUNT(*) events FROM lca_events e LEFT JOIN lca_devices d ON d.device_id=e.device_id WHERE e.occurred_at>=? AND d.status<>'ignored' GROUP BY e.device_id ORDER BY events DESC LIMIT 10", (since,)).fetchall()]
            routes = [dict(r) for r in c.execute("""SELECT e.origin_location_name,e.adjacent_location_name,e.direction_hint,
                COUNT(*) evidence_count,MAX(e.occurred_at) last_seen
                FROM lca_events e JOIN lca_devices d ON d.device_id=e.device_id
                WHERE e.occurred_at>=? AND e.kind='interaction' AND d.status<>'ignored'
                  AND (e.direction_hint IS NOT NULL OR e.adjacent_location_name IS NOT NULL)
                GROUP BY e.origin_location_name,e.adjacent_location_name,e.direction_hint
                ORDER BY evidence_count DESC LIMIT 10""", (since,)).fetchall()]
            recent = [dict(r) for r in c.execute("SELECT e.*,d.name device_name FROM lca_events e LEFT JOIN lca_devices d ON d.device_id=e.device_id WHERE e.occurred_at>=? AND d.status<>'ignored' ORDER BY e.occurred_at DESC LIMIT 30", (since,)).fetchall()]
        return {"period_hours": hours, "summary": totals, "by_hour": by_hour, "top_devices": top, "route_evidence": routes, "recent_events": recent, "updated_at": datetime.now(timezone.utc).isoformat()}
